web:
  image: nginx:latest
  ports:
    - 8086:80
  volumes:
    - ./src:/code:ro
    - ./site.conf:/etc/nginx/conf.d/site.conf:ro
  links:
    - php

php:
  build: ./.docker/php
  volumes:
    - ./src:/code:ro
